name: Destroy-Prod-Infra.$(BuildID)

trigger: 
 - none

stages:
   - stage: DestroyProduction
     displayName: 'Destroy Production Environment'
     jobs:
      - deployment: DestroyProductionDeployment
        displayName: 'Destroy Production Infrastructure'
        pool:
          vmImage: 'ubuntu-latest'
        variables:
        - template: variables-prod.yml
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - script: |
                  if [ -s "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars" ]; then
                    echo "" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  fi
                  echo "linux_vm_admin_username = \"$(linux_vm_admin_username)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "linux_vm_admin_password = \"$(linux_vm_admin_password)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "linux_vm_jumpbox_admin_username = \"$(linux_vm_jumpbox_admin_username)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "linux_vm_jumpbox_admin_password = \"$(linux_vm_jumpbox_admin_password)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "windows_vm_admin_username = \"$(windows_vm_admin_username)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "windows_vm_admin_password = \"$(windows_vm_admin_password)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "psql_admin_username = \"$(psql_admin_username)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                  echo "psql_admin_password = \"$(psql_admin_password)\"" >> "$(System.DefaultWorkingDirectory)/environments/production/terraform.tfvars"
                displayName: 'Append variables to terraform.tfvars'

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
                displayName: 'Install TF'
                inputs:
                  terraformVersion: 'latest'

              - task: TerraformTaskV4@4
                displayName: 'tf init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/environments/production'
                  backendServiceArm: 'sc-searateserp-prod'
                  backendAzureRmResourceGroupName: 'rg-searates-erp-shared-uaenorth'
                  backendAzureRmStorageAccountName: 'stsearateserptfshared'
                  backendAzureRmContainerName: 'terraform-erp-prod-state-container'
                  backendAzureRmKey: 'terraform.tfstate'

              - task: TerraformTaskV4@4
                displayName: 'tf destroy'
                inputs:
                  provider: 'azurerm'
                  command: 'destroy'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/environments/production'
                  commandOptions: '-auto-approve'
                  environmentServiceNameAzureRM: 'sc-searateserp-prod'